apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db-controller
  namespace: pg-db-controller
spec:
  selector:
    matchLabels:
      app: pg-db-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-db-controller
    spec:
      serviceAccountName: pg-db-controller
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "external"
          effect: "NoSchedule"
      containers:
        - name: pg-db-controller
          image: pg-db-controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
