apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: pg-db-controller-secret
  namespace: pg-db-controller
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: pg-db-controller-of-k6
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReferences:
    - secretName: pg-db-controller-managed-secrets
      secretNamespace: pg-db-controller
      creationPolicy: "Owner"
